In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv("/content/drive/MyDrive/datasets/heart disease classification dataset.csv")
data

Unnamed: 0  age     sex  cp  trestbps   chol  fbs  restecg  thalach  \
0             0   63    male   3     145.0  233.0    1        0    150.0   
1             1   37    male   2     130.0  250.0    0        1    187.0   
2             2   41  female   1     130.0  204.0    0        0    172.0   
3             3   56    male   1     120.0  236.0    0        1    178.0   
4             4   57  female   0       NaN  354.0    0        1    163.0   
..          ...  ...     ...  ..       ...    ...  ...      ...      ...   
298         298   57  female   0     140.0  241.0    0        1    123.0   
299         299   45    male   3     110.0  264.0    0        1    132.0   
300         300   68    male   0     144.0  193.0    1        1    141.0   
301         301   57    male   0       NaN  131.0    0        1    115.0   
302         302   57  female   1     130.0  236.0    0        0    174.0   

     exang  oldpeak  slope  ca  thal target  
0        0      2.3      0   0     1    yes  
1        0      3.5      0   0     2    yes  
2        0      1.4      2   0     2    yes  
3        0      0.8      2   0     2    yes  
4        1      0.6      2   0     2    yes  
..     ...      ...    ...  ..   ...    ...  
298      1      0.2      1   0     3     no  
299      0      1.2      1   0     3     no  
300      0      3.4      1   2     3     no  
301      1      1.2      1   1     3     no  
302      0      0.0      1   1     2     no  

[303 rows x 15 columns]

In [ ]:
data.isnull().sum()

Unnamed: 0    0
age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
target        0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
simple=SimpleImputer(strategy="mean",missing_values=np.nan)
simple.fit(data.iloc[:,4:6])
data.iloc[:,4:6]=simple.transform(data.iloc[:,4:6])

In [ ]:
from sklearn.impute import SimpleImputer
simple=SimpleImputer(strategy="mean",missing_values=np.nan)
simple.fit(data.iloc[:,8:9])
data.iloc[:,8:9]=simple.transform(data.iloc[:,8:9])

In [ ]:
data

Unnamed: 0  age     sex  cp    trestbps   chol  fbs  restecg  thalach  \
0             0   63    male   3  145.000000  233.0    1        0    150.0   
1             1   37    male   2  130.000000  250.0    0        1    187.0   
2             2   41  female   1  130.000000  204.0    0        0    172.0   
3             3   56    male   1  120.000000  236.0    0        1    178.0   
4             4   57  female   0  131.712375  354.0    0        1    163.0   
..          ...  ...     ...  ..         ...    ...  ...      ...      ...   
298         298   57  female   0  140.000000  241.0    0        1    123.0   
299         299   45    male   3  110.000000  264.0    0        1    132.0   
300         300   68    male   0  144.000000  193.0    1        1    141.0   
301         301   57    male   0  131.712375  131.0    0        1    115.0   
302         302   57  female   1  130.000000  236.0    0        0    174.0   

     exang  oldpeak  slope  ca  thal target  
0        0      2.3      0   0     1    yes  
1        0      3.5      0   0     2    yes  
2        0      1.4      2   0     2    yes  
3        0      0.8      2   0     2    yes  
4        1      0.6      2   0     2    yes  
..     ...      ...    ...  ..   ...    ...  
298      1      0.2      1   0     3     no  
299      0      1.2      1   0     3     no  
300      0      3.4      1   2     3     no  
301      1      1.2      1   1     3     no  
302      0      0.0      1   1     2     no  

[303 rows x 15 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,2:3]=lb.fit_transform(data.iloc[:,2:3])

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
<ipython-input-9-0eb8564eee4f>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.iloc[:,2:3]=lb.fit_transform(data.iloc[:,2:3])


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,-1,]=lb.fit_transform(data.iloc[:,-1,])

<ipython-input-10-5144f7610a6d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.iloc[:,-1,]=lb.fit_transform(data.iloc[:,-1,])


In [ ]:
#splitting the data into train and test
x=data.iloc[:,1:-1]
x

age  sex  cp    trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3  145.000000  233.0    1        0    150.0      0      2.3   
1     37    1   2  130.000000  250.0    0        1    187.0      0      3.5   
2     41    0   1  130.000000  204.0    0        0    172.0      0      1.4   
3     56    1   1  120.000000  236.0    0        1    178.0      0      0.8   
4     57    0   0  131.712375  354.0    0        1    163.0      1      0.6   
..   ...  ...  ..         ...    ...  ...      ...      ...    ...      ...   
298   57    0   0  140.000000  241.0    0        1    123.0      1      0.2   
299   45    1   3  110.000000  264.0    0        1    132.0      0      1.2   
300   68    1   0  144.000000  193.0    1        1    141.0      0      3.4   
301   57    1   0  131.712375  131.0    0        1    115.0      1      1.2   
302   57    0   1  130.000000  236.0    0        0    174.0      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [ ]:
y=data.iloc[:,-1:]
y

target
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train,y_train

(     age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
 74    43    0   2     122.0  213.0    0        1    165.0      0      0.2   
 153   66    0   2     146.0  278.0    0        0    152.0      0      0.0   
 64    58    1   2     140.0  211.0    1        0    165.0      0      0.0   
 296   63    0   0     124.0  197.0    0        1    136.0      1      0.0   
 287   57    1   1     154.0  232.0    0        0    164.0      0      0.0   
 ..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...   
 251   43    1   0     132.0  247.0    1        0    143.0      1      0.1   
 192   54    1   0     120.0  188.0    0        1    113.0      0      1.4   
 117   56    1   3     120.0  193.0    0        0    162.0      0      1.9   
 47    47    1   2     138.0  257.0    0        0    156.0      0      0.0   
 172   58    1   1     120.0  284.0    0        0    160.0      0      1.8   
 
      slope  ca  thal  
 74       1   0     2  
 153      1   

In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score
r2_score(y_pred,y_test)

0.3222222222222223

In [ ]:
print(accuracy_score(y_pred,y_test))

0.8360655737704918


In [ ]:
confusion_matrix(y_pred,y_test)

array([[21,  4],
       [ 6, 30]])

In [ ]:
acc=(21+30)/(21+4+6+30)
acc

0.8360655737704918

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.78      0.84      0.81        25
           1       0.88      0.83      0.86        36

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61



In [ ]:
#using the K-fold validation
from sklearn.model_selection import cross_val_score
accur=cross_val_score(estimator=lr,X=x_train,y=y_train,cv=15)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

In [ ]:
print("Accuracy {:.2f}%".format(accur.mean()*100))

Accuracy 82.75%


In [ ]:
print("Strandard Deviation:{:.2f}%".format(accur.std()*100))

Strandard Deviation:8.53%


In [ ]:
#grid search
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[0.25,0.5,0.75,1]}]
grid_search=GridSearchCV(estimator=lr,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search.fit(x_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_
print("Best Accuarcy:{:.2f}%".format(best_accuracy*100))
print("Best parameters:",best_parameters)

Best Accuarcy:82.67%
Best parameters: {'C': 0.25}


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#Support Vector machine
from sklearn.svm import SVC
class2=SVC(kernel="poly")
class2.fit(x_train,y_train)


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='poly')

In [ ]:
y_pred2=class2.predict(x_test)
y_pred2

array([0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.model_selection import cross_val_score
accuracy2=cross_val_score(estimator=class2,X=x_train,y=y_train,cv=10)
print("Accuracy of SVM:{:.2f}%".format(accuracy2.mean()*100))
print("Strandard Deviation of SvM:{:.2f}%".format(accuracy2.std()*100))

Accuracy of SVM:66.12%
Strandard Deviation of SvM:7.34%


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example 

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters2=[{"C":[0.25,0.5,0.75,1],'kernel':['rbf','linear']}]
grid_search2=GridSearchCV(estimator=class2,param_grid=parameters2,scoring="accuracy",cv=10,n_jobs=-1)
grid_search2.fit(x_train,y_train)
best_accuracy=grid_search2.best_score_
best_parameters=grid_search2.best_params_
print("best_accuracy of svm :{:.2f}%".format(best_accuracy*100))
print("best parameters of svm:",best_parameters)



best_accuracy of svm :81.85%
best parameters of svm: {'C': 0.75, 'kernel': 'linear'}


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred2,y_test))


0.6557377049180327


In [ ]:
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       0.44      0.67      0.53        18
           1       0.82      0.65      0.73        43

    accuracy                           0.66        61
   macro avg       0.63      0.66      0.63        61
weighted avg       0.71      0.66      0.67        61



In [ ]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
class3=DecisionTreeClassifier()
class3.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred3=class3.predict(x_test)
y_pred3

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:
#k fold classifier
from sklearn.model_selection import cross_val_score
accuracy3=cross_val_score(estimator=class3,X=x_train,y=y_train,cv=10)
print("Accuracy of decision tree {:.2f}%".format(accuracy3.mean()*100))
print("Strandard deviation of decision tree {:.2f}%".format(accuracy3.std()*100))

Accuracy of decision tree 78.22%
Strandard deviation of decision tree 8.23%


In [ ]:
#grid search CV
from sklearn.model_selection import GridSearchCV
parameter3=[{"criterion":['gini','entropy','log_loss']}]
grid_search3=GridSearchCV(estimator=class3,param_grid=parameter3,scoring="accuracy",cv=10,n_jobs=-1)
grid_search3.fit(x_train,y_train)
best_accuracy=grid_search3.best_score_
best_parameters=grid_search3.best_params_
print("Best Accuracy of decision tree {:.2f}%".format(best_accuracy*100))
print("Best paramters:",best_parameters)

Best Accuracy of decision tree 79.87%
Best paramters: {'criterion': 'gini'}


In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred3,y_test))

0.819672131147541


In [ ]:
print(classification_report(y_pred3,y_test))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80        28
           1       0.82      0.85      0.84        33

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [ ]:
#Randomforest
from sklearn.ensemble import RandomForestClassifier
class4=RandomForestClassifier(n_estimators=100)
class4.fit(x_train,y_train)

<ipython-input-33-0081c0bf117c>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  class4.fit(x_train,y_train)


RandomForestClassifier()

In [ ]:
y_pred4=class4.predict(x_test)
y_pred4

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.model_selection import cross_val_score
accuracy4=cross_val_score(estimator=class4,X=x_train,y=y_train,cv=10)
print("Accuracy of random forest {:.2f}%".format(accuracy4.mean()*100))
print("strandard deviation of randomforest {:.2f}%".format(accuracy4.std()*100))

/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 

Accuracy of random forest 81.85%
strandard deviation of randomforest 4.84%


In [ ]:
#grid search CV
from sklearn.model_selection import GridSearchCV
parameters=[{"criterion":['gini','entropy','log_loss'],"n_estimators":[100]}]
grid_search4=GridSearchCV(estimator=class4,param_grid=parameters,scoring="accuracy",cv=10,n_jobs=-1)
grid_search4.fit(x_train,y_train)
best_accuracy=grid_search4.best_score_
best_parameters=grid_search4.best_params_
print("Best Accuracy of random forest {:.2f}%".format(best_accuracy*100))
print("Best parameters of random forest ",best_parameters)


Best Accuracy of random forest 84.33%
Best parameters of random forest  {'criterion': 'log_loss', 'n_estimators': 100}


/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


In [ ]:
print(accuracy_score(y_pred4,y_test))

0.8524590163934426


In [ ]:
print(classification_report(y_pred4,y_test))

              precision    recall  f1-score   support

           0       0.81      0.85      0.83        26
           1       0.88      0.86      0.87        35

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



In [ ]:
#XG boost classifier
import xgboost as xgb
class5=xgb.XGBClassifier()
class5.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
y_pred5=class5.predict(x_test)
y_pred5

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:
# k fold validation
from sklearn.model_selection import cross_val_score
accuracy5=cross_val_score(estimator=class5,X=x_train,y=y_train,cv=10)
print("Accuracy of xgboost {:.2f}%".format(accuracy5.mean()*100))
print("Strandard deviation of xgboost {:.2f}%".format(accuracy5.std()*100))

Accuracy of xgboost 80.60%
Strandard deviation of xgboost 5.81%


In [ ]:
#grid search cv
from sklearn.model_selection import GridSearchCV
parameters=[{"booster":["gbtree",'gblinear','dart'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search5=GridSearchCV(estimator=class5,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search5.fit(x_train,y_train)
best_accuracy=grid_search5.best_score_
best_parameters=grid_search5.best_params_
print("Best Accuracy of xgboost {:.2f}%".format(best_accuracy*100))
print("best parameter of xgboost:",best_parameters)

Best Accuracy of xgboost 82.70%
best parameter of xgboost: {'booster': 'gbtree', 'gamma': 0.2}


In [ ]:
print(accuracy_score(y_pred5,y_test))

0.8032786885245902


In [ ]:
print(classification_report(y_pred5,y_test))

              precision    recall  f1-score   support

           0       0.81      0.76      0.79        29
           1       0.79      0.84      0.82        32

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61



In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_pred5,y_test))

[[22  7]
 [ 5 27]]


In [ ]:
# Tuning the logistic regression for the best parameter
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=0.25)
lr.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.25)

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:
print(accuracy_score(y_pred,y_test))

0.8360655737704918


In [ ]:
#tuning the best parameter for the SVM
from sklearn.svm import SVC
class2=SVC(C=0.75,kernel='linear')
class2.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.75, kernel='linear')

In [ ]:
y_pred2=class2.predict(x_test)

In [ ]:
accuracy_score(y_pred2,y_test)

0.819672131147541

In [ ]:
#tuning the best parameter for the decision tree classifier
from sklearn.tree import DecisionTreeClassifier
class3=DecisionTreeClassifier(criterion='gini')
class3.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred3=class3.predict(x_test)


In [ ]:
accuracy_score(y_pred3,y_test)

0.7868852459016393

In [ ]:
#tuning the parameter for the random forest
from sklearn.ensemble import RandomForestClassifier
class4=RandomForestClassifier(criterion='log_loss',n_estimators=100)
class4.fit(x_train,y_train)

<ipython-input-67-80c16fbc403a>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  class4.fit(x_train,y_train)


RandomForestClassifier(criterion='log_loss')

In [ ]:
y_pred4=class4.predict(x_test)

In [ ]:
accuracy_score(y_pred4,y_test)

0.8688524590163934

In [ ]:
from xgboost.sklearn import XGBClassifier
#tuning the xgboost for the best parameter
import xgboost as xgb
class5=XGBClassifier(booster='gbtree',gamma=0.2)
class5.fit(x_train,y_train)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=0.2, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
y_pred5=class5.predict(x_test)

In [ ]:
accuracy_score(y_pred5,y_test)


0.819672131147541

In [ ]:
pip install gradio


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 36.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.2/286.2 kB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.3/75.3 kB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 19.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.5/129.5 kB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 

In [ ]:
import gradio as gr


In [ ]:
def greet(name):
  return 'Hello '+name+' !'
demo=gr.Interface(fn=greet,
                  inputs=gr.Textbox(lines=2,placeholder="Enter Name"),outputs="text")
demo.launch()


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.

To create a public link, set `share=True` in `launch()`.


<IPython.core.display.Javascript object>

In [ ]:
def greet(name,is_morning,temperature):
  saluation="Good morning" if is_morning else "good evening"
  greeting=f"{saluation}{name}.Its {temperature} is in the morning"
  celsius=(temperature-32)*5/9
  return greeting,round(celsius,2)
demo=gr.Interface(fn=greet,
                  inputs=["text","checkbox",gr.Slider(0,100)],
                  outputs=["text","number"])
demo.launch()


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.

To create a public link, set `share=True` in `launch()`.


<IPython.core.display.Javascript object>

In [ ]:
import gradio as gr
import warnings
warnings.filterwarnings("ignore")

In [ ]:
def Heartdisease_classification(age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal):
    x = np.array([age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal])
    prediction =  class4.predict(x.reshape(1,-1))
    if prediction == [1] :
        prediction = 'heart disease'
    else:
        prediction ='No heart disease'
    return prediction
outputs = gr.outputs.Textbox()
heartdisease_classification = gr.Interface(fn=Heartdisease_classification, inputs=["number","number","number","number","number","number","number","number","number","number","number","number","number"], outputs=outputs, description='Heart Disease Prediction')




In [ ]:
heartdisease_classification.launch(share = True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://cce282e2afac6953b3.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
